### ISSUE TITLE
support unprefixed vendors

### ISSUE THREAD

**Issue by contra** [HenrikJoreteg/webrtcsupport#18]
there are plenty of vendors in the wild without prefixes (iosrtc) so why does this not work with those?

**Comment by RangerMauve** [comment]
In terms of iosRTC, they can't provide the globals until the "deviceready" event is emitted. This module detects the globals when it's initially required, so you might have a timing issue.

+1 for supporting unprefixed modules, though.

**Comment by contra** [comment]
@RangerMauve Sure, but that isn't of any concern to this module or any other one.

```js
document.addEventListener('deviceready', function(){
  var rtc = require('webrtcsupport');
});
```

and for temasys it would be

```js
var adapter = require('adapterjs');
adapter.webRTCReady(function(){
  var rtc = require('webrtcsupport');
});
```


Want a web app that can use WebRTC in any browser, operating system, and any mobile device?

```js
document.addEventListener('deviceready', function(){
  var adapter = require('adapterjs');
  adapter.webRTCReady(function(){
    var rtc = require('webrtcsupport');
  });
});
```

Too bad webrtcsupport (and the whole ecosystem of modules that rely on it) are stuck on chrome/firefox only because they want to neglect this simple fix 😱

**Comment by RangerMauve** [comment]
I agree fully.

**Comment by fippo** [comment]
Your concern is that this module doesn't do
```
var PC = window.RTCPeerConnection || window.mozRTCPeerConnection || window.webkitRTCPeerConnection;
```
?

Interested how you're getting this to work in Microsoft Edge (since you said 'any browser)

**Comment by RangerMauve** [comment]
My hope is that edge will hurry up with their ORTC crap so that someone can polyfill WebRTC on top of it.

**Comment by contra** [comment]
@fippo temasys is going to handle edge https://github.com/Temasys/AdapterJS/issues/99

Also yes, the issue was that easy to fix which is why I was so confused about why it was open for so long and such a problem to fix.

**Comment by contra** [comment]
I think there still might be some problems with the way the browser detection is done (since it assumes if webkitPeerConnection exists then it is chrome, even though webkitPeerConnection can also exist on safari/ie via temasys) but I will open further tickets as needed. Thank you for fixing this.

**Comment by RangerMauve** [comment]
My take on the version/prefix part of this library is that it's not 100% needed.

**Comment by fippo** [comment]
I have gradually gotten rid of this library actually in favor of adapter. But things take time.
