### ISSUE TITLE
supportDataChannel no longer works

### ISSUE THREAD

**Issue by xdumaine** [HenrikJoreteg/webrtcsupport#21]
https://github.com/HenrikJoreteg/webrtcsupport/blob/master/index-browser.js#L34

`window.RTCPeerConnection.prototype.createDataChannel` no longer exists. :confused:

**Comment by fippo** [comment]
window.RTCDataChannel never existed but the code does not say that?

**Comment by RangerMauve** [comment]
Did you maybe mean that `RTCPeerConnection.prototype.createDataChannel` has been deprecated? Do you have a link to your source?

**Comment by xdumaine** [comment]
@fippo my mistake, I meant `window.RTCPeerConnection`. need coffee...

**Comment by xdumaine** [comment]
See #22
