### ISSUE TITLE
Uncaught ReferenceError: isChrome is not defined

### ISSUE THREAD

**Issue by RangerMauve** [HenrikJoreteg/webrtcsupport#8]
Hey, using the latest version, I seem to be getting this error [here](https://github.com/HenrikJoreteg/webrtcsupport/blob/3c0d92d9257d7799036371efe69ecccd840a31bd/index-browser.js#L27). Not sure what caused this, but it seems that your isChrome and isFirefox variables are no longer getting defined.

**Comment by fippo** [comment]
ah, merge mistake :-(
Fixed in 1.2.2

**Comment by RangerMauve** [comment]
:P It's always a pleasant surprise when that happens, eh. Thanks!
