### ISSUE TITLE
Detect OpenWebRTC-based browser

### ISSUE THREAD

**Issue by stefanalund** [HenrikJoreteg/webrtcsupport#9]
Detect support for OpenWebRTC-based browsers, such as Bowser: http://www.openwebrtc.io/bowser/

**Comment by fippo** [comment]
@stefanalund is this fixed by https://github.com/HenrikJoreteg/webrtcsupport/pull/19 -- not sure what is required.

**Comment by stefanalund** [comment]
No, it does not seem to be enough. You are requiring VP8 and testing it in a flawed way. I would argue for removing this requirement altogether. Or you could add a requirement for H.264 and subsequently see Chrome "not support WebRTC" :smirk: 

https://github.com/HenrikJoreteg/webrtcsupport/blob/master/index-browser.js#L29

**Comment by fippo** [comment]
vp8 requirement was removed at some point in 2015.
